### ISSUE TITLE
netscaler-node-controller repo is not functional

### ISSUE THREAD

**Issue by patsch9** [netscaler/netscaler-helm-charts#185]
Wrong values in:

https://github.com/netscaler/netscaler-helm-charts/blob/b02cf1e0e9ec0e0507cfcadecf5ab9391d5197f3/netscaler-node-controller/templates/_helpers.tpl#L87-L92

in cnc chart it is .name

https://github.com/netscaler/netscaler-helm-charts/blob/b02cf1e0e9ec0e0507cfcadecf5ab9391d5197f3/citrix-node-controller/templates/_helpers.tpl#L87-L90

caused this error: template: netscaler-node-controller/templates/deployment.yaml:63:20: executing "netscaler-node-controller/templates/deployment.yaml" at <include "netscaler-k8s-node-controller.nsncConfigMap" .>: error calling include: template: netscaler-node-controller/templates/_helpers.tpl:89:37: executing "netscaler-k8s-node-controller.nsncConfigMap" at <63>: wrong type for value; expected string; got map[string]interface {}]

**Comment by patsch9** [comment]
can you please fix the issue?

**Comment by priyankash-citrix** [comment]
Hi @patsch9, the mentioned issue has been fixed in the latest NetScaler Node Controller helm chart.
Please try and let us know if you have any further queries.
