### ISSUE TITLE
Getting error - line feed on citrix-k8s-ingress.yaml:12 

### ISSUE THREAD

**Issue by MalekGD86** [netscaler/netscaler-helm-charts#193]
in the commit  52c95e3, a line feed has been inserted causing charts not to work anymore on install / upgrade.
this error has been raised : 

Error: UPGRADE FAILED: parse error at (citrix-cloud-native/charts/cic/templates/citrix-k8s-ingress.yaml:12): unterminated quoted string

**Comment by subashd** [comment]
Hi @MalekGD86 ,
Could you please share output of `helm template cic netscaler/citrix-ingress-controller`?

**Comment by MalekGD86** [comment]
`---
# Source: citrix-ingress-controller/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cic-citrix-ingress-controller
  namespace: default
---
# Source: citrix-ingress-controller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cic-cic-configmap
  namespace: default
data:
  LOGLEVEL: "info"
  JSONLOG: "false"
  NS_PROTOCOL: "https"
  NS_PORT: "443"
---
# Source: citrix-ingress-controller/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cic-citrix-ingress-controller
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "secrets", "routes", "nodes", "namespaces", "configmaps", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies", "continuousdeployments", "authpolicies", "ratelimits", "listeners", "httproutes", "wafs", "apigatewaypolicies", "bots", "corspolicies", "appqoepolicies", "wildcarddnsentries"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies/status", "continuousdeployments/status", "authpolicies/status", "ratelimits/status", "listeners/status", "httproutes/status", "wafs/status", "apigatewaypolicies/status", "bots/status", "corspolicies/status", "appqoepolicies/status", "wildcarddnsentries/status"]
    verbs: ["patch"]
  - apiGroups: ["citrix.com"]
    resources: ["vips"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["crd.projectcalico.org"]
    resources: ["ipamblocks"]
    verbs: ["get", "list", "watch"]
---
# Source: citrix-ingress-controller/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cic-citrix-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cic-citrix-ingress-controller
subjects:
- kind: ServiceAccount
  name: cic-citrix-ingress-controller
  namespace: default
---
# Source: citrix-ingress-controller/templates/citrix-k8s-ingress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-citrix-ingress-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: cic-citrix-ingress-controller
  replicas: 1
  template:
    metadata:
      name: cic
      labels:
        app: cic-citrix-ingress-controller
      annotations:
    spec:
      serviceAccountName: cic-citrix-ingress-controller
      containers:
      - name: cic
        image: "quay.io/citrix/citrix-k8s-ingress-controller:2.0.6"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/readiness
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              FILE_PATH="$LIVENESS_FILE_PATH"
              [ -f "$FILE_PATH" ] && [ $(( $(date +%s) - $(stat -c %Y "$FILE_PATH") )) -lt 60 ] && exit 0 || exit 1
          initialDelaySeconds: 30
          periodSeconds: 60
        args:
          - --configmap
            default/cic-cic-configmap
          - --feature-node-watch
            false
          - --enable-cnc-pbr
            false
          - --update-ingress-status
            yes
        env:
        - name: "NS_IP"
          value: ""
        - name: "NS_NITRO_READ_TIMEOUT"
          value: "20"
        - name: "LIVENESS_FILE_PATH"
          value: '/tmp/liveness_path.log'
        - name: "NS_USER"
          valueFrom:
            secretKeyRef:
              name:
              key: username
        - name: "NS_PASSWORD"
          valueFrom:
            secretKeyRef:
              name:
              key: password
        - name: "EULA"
          value: "false"
        - name: "NS_APPS_NAME_PREFIX"
          value: "k8s"
        - name: "NS_MC_PREFIX"
          value: "mc"
        - name: "PLATFORM"
          value: "KUBERNETES"
        - name: "BGP_ADVERTISEMENT"
          value: "false"
        resources:
            limits: {}
            requests:
              cpu: 32m
              memory: 128Mi
`

**Comment by subashd** [comment]
Thank you @MalekGD86 
The above output looks fine. 
Could you please share the command you tried to upgrade or install?
Also which version of CIC are you using and upgrading to which version?

**Comment by MalekGD86** [comment]
i've installed this repo :

**Comment by MalekGD86** [comment]
I've installed this repo: 

- helm repo add netscaler https://netscaler.github.io/netscaler-helm-charts/
- helm upgrade --install cic netscaler/citrix-cloud-native -f cic_ipam.yaml

It installed the last version of the helm chart, i guess.
The yaml file didn't change since i've installed it sucessfully

the output of the command is the error raised in the main comment.

**Comment by subashd** [comment]
Could you please share the cic_ipam.yaml as well?

**Comment by subashd** [comment]
Thank you @MalekGD86 
I have fixed the issue. Could you please try once?

**Comment by MalekGD86** [comment]
work perfectly ! 
thank you for your quick fix!

**Comment by subashd** [comment]
Thank you @MalekGD86 
Also, you can provide more details on your requirement over an [email](mailto:netscaler-appmodernization@cloud.com)
